In [1]:
import pickle

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Algerian_forest_fire_cleaned_data.csv')
df.head()

day  month  year  Temperature  RH  Ws  Rain  FFMC  DMC    DC  ISI  BUI  \
0    1      6  2012           29  57  18   0.0  65.7  3.4   7.6  1.3  3.4   
1    2      6  2012           29  61  13   1.3  64.4  4.1   7.6  1.0  3.9   
2    3      6  2012           26  82  22  13.1  47.1  2.5   7.1  0.3  2.7   
3    4      6  2012           25  89  13   2.5  28.6  1.3   6.9  0.0  1.7   
4    5      6  2012           27  77  16   0.0  64.8  3.0  14.2  1.2  3.9   

   FWI  Classes  Region  
0  0.5        0       1  
1  0.4        0       1  
2  0.1        0       1  
3  0.0        0       1  
4  0.5        0       1

In [4]:
df.columns

Index(['day', 'month', 'year', 'Temperature', 'RH', 'Ws', 'Rain', 'FFMC',
       'DMC', 'DC', 'ISI', 'BUI', 'FWI', 'Classes', 'Region'],
      dtype='object')

In [5]:
X = df.loc[:,['Temperature', 'Ws', 'FFMC','DMC','ISI']]

y = df['FWI']

In [6]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.25)

In [7]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((182, 5), (61, 5), (182,), (61,))

In [8]:
# Random forest

from sklearn.ensemble import RandomForestRegressor
RF = RandomForestRegressor(random_state=0)
RF.fit(x_train, y_train)

RandomForestRegressor(random_state=0)

In [9]:
y_pred = RF.predict(x_test)
diff = pd.DataFrame({'Actual': y_test, 'pred': y_pred})
diff.head()

Actual    pred
140     0.4   0.389
95      0.5   0.613
6       7.2   7.366
41      0.9   0.851
110     9.7  10.231

In [10]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.9709252558567671

In [11]:
import warnings
warnings.filterwarnings('ignore')

In [12]:
RF.predict([[33,14,81.1,8.1,2.6]])

array([2.873])

In [13]:
with open('model_reg.pickle', 'wb') as f:
    pickle.dump(RF,f)

In [15]:
with open('model_reg.pickle', 'rb') as f:
    RF_reg_model = pickle.load(f)

In [16]:
RF_reg_model.predict([[33,14,81.1,8.1,2.6]])

array([2.873])

In [17]:
import bz2,pickle
file = bz2.BZ2File('Regression_trial.pkl','wb')
pickle.dump(RF,file)
file.close()

In [18]:
R_pickle = bz2.BZ2File('Regression_trial.pkl', 'rb')
model_R = pickle.load(R_pickle)

In [19]:
model_R.predict([[33,14,81.1,8.1,2.6]])

array([2.873])